name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - run: npm ci
      - run: npm run build --if-present
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          # ftp server
          server: 108.167.151.65
          # ftp username
          username: ultrat09
          # ftp password
          password: Ultratribrasil2025*
          # Server port to connect to (read your web hosts docs)
          port: 21
          # protocol to deploy with - ftp, ftps, or ftps-legacy
          protocol: ftp
          # Folder to upload from, must end with trailing slash /
          local-dir: dist/
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: public_html/
          # Prints which modifications will be made with current config options, but doesnt actually make any changes
          dry-run: true
          # Deletes ALL contents of server-dir, even items in excluded with exclude argument
          
          
